import { User, Module, Task, Comment } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Alice Martin',
    email: 'alice@example.com',
    role: 'admin',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Bob Dupont',
    email: 'bob@example.com',
    role: 'developer',
    createdAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    name: 'Claire Moreau',
    email: 'claire@example.com',
    role: 'designer',
    createdAt: new Date('2024-01-25'),
  },
  {
    id: '4',
    name: 'David Bernard',
    email: 'david@example.com',
    role: 'manager',
    createdAt: new Date('2024-02-01'),
  },
];

export const mockModules: Module[] = [
  {
    id: '1',
    name: 'Authentication',
    description: 'Module de gestion des utilisateurs et authentification',
    color: '#3B82F6',
    createdAt: new Date('2024-01-10'),
  },
  {
    id: '2',
    name: 'Dashboard',
    description: 'Tableau de bord et statistiques',
    color: '#10B981',
    createdAt: new Date('2024-01-12'),
  },
  {
    id: '3',
    name: 'API',
    description: 'Services backend et API REST',
    color: '#F59E0B',
    createdAt: new Date('2024-01-15'),
  },
  {
    id: '4',
    name: 'UI/UX',
    description: 'Interface utilisateur et expérience',
    color: '#EF4444',
    createdAt: new Date('2024-01-18'),
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Créer la page de connexion',
    description: 'Implémenter l\'interface de connexion avec validation',
    assignedTo: '2',
    moduleId: '1',
    status: 'completed',
    priority: 'high',
    estimatedTime: 8,
    actualTime: 6,
    comments: [
      {
        id: '1',
        text: 'Design validé, prêt pour le développement',
        authorId: '3',
        createdAt: new Date('2024-01-20'),
      },
    ],
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-22'),
    dueDate: new Date('2024-01-25'),
  },
  {
    id: '2',
    title: 'Développer l\'API d\'authentification',
    description: 'Créer les endpoints pour login/logout/register',
    assignedTo: '2',
    moduleId: '3',
    status: 'in-progress',
    priority: 'high',
    estimatedTime: 12,
    actualTime: 8,
    comments: [],
    createdAt: new Date('2024-01-18'),
    updatedAt: new Date('2024-01-28'),
    dueDate: new Date('2024-02-05'),
  },
  {
    id: '3',
    title: 'Concevoir les graphiques du dashboard',
    description: 'Créer les maquettes pour les statistiques',
    assignedTo: '3',
    moduleId: '4',
    status: 'review',
    priority: 'medium',
    estimatedTime: 6,
    actualTime: 7,
    comments: [
      {
        id: '2',
        text: 'Première version terminée, en attente de feedback',
        authorId: '3',
        createdAt: new Date('2024-01-25'),
      },
    ],
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-26'),
    dueDate: new Date('2024-02-01'),
  },
  {
    id: '4',
    title: 'Implémenter les graphiques',
    description: 'Développer les composants de visualisation',
    assignedTo: '2',
    moduleId: '2',
    status: 'todo',
    priority: 'medium',
    estimatedTime: 10,
    actualTime: 0,
    comments: [],
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
    dueDate: new Date('2024-02-08'),
  },
  {
    id: '5',
    title: 'Tests unitaires API',
    description: 'Écrire les tests pour tous les endpoints',
    assignedTo: '2',
    moduleId: '3',
    status: 'todo',
    priority: 'low',
    estimatedTime: 8,
    actualTime: 0,
    comments: [],
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
    dueDate: new Date('2024-02-10'),
  },
];